url: http://homes4u.us

# Site settings
title: Brenda Brown Realtor

email: brendareidbrown@gmail.com

description: "Brenda Brown Realtor for Homes in Alabama, homes4u, homes for you, homes 4 you, the goodson group"


# Team names, titles and social links
people:
- name: Brenda Brown
  pic: 1
  position: Lead Realtor
  social:
    - title: facebook
      url: https://www.facebook.com/brendabrownrealtor/?fref=ts
    - title: linkedin
      url: https://www.linkedin.com/in/brendabrownrealtor

- name: Ting Phan
  pic: 2
  position: Lead Developer
  social:
    - title: facebook
      url: https://www.facebook.com/brendabrownrealtor/?fref=ts
    - title: linkedin
      url: https://www.linkedin.com/in/thanh-phan-b7022115

- name: Sarah Reid
  pic: 3
  position: Lead Processor
  social:
    - title: facebook
      url: https://www.facebook.com/brenda.reid.brown

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/brendabrownrealtor/?fref=ts
  - title: linkedin
    url: https://www.linkedin.com/in/brendabrownrealtor

# Postal address (add as many lines as necessary)
address:
  - line: 1975 Berry Chase Pl.
  - line: Montgomery, AL 36117

# Build settings
markdown: kramdown
permalink: pretty
